# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/sgp311/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#    vendor/sony/sgp311/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
#    vendor/sony/sgp311/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
#    vendor/sony/sgp311/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
#    vendor/sony/sgp311/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so

PRODUCT_PLATFORM := Lagan
$(call inherit-product, $(LOCAL_PATH)/sgp311-partial.mk)
$(call inherit-product, vendor/sony/lagan/lagan-partial.mk)
$(call inherit-product-if-exists, vendor/qcom/lagan/lagan-partial.mk)

PRODUCT_COPY_FILES += \
    vendor/sony/sgp311/proprietary/lib/libOmxVenc.so:system/lib/libOmxVenc.so \
    vendor/sony/sgp311/proprietary/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    vendor/sony/sgp311/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/sony/sgp311/proprietary/etc/hw_config.sh:system/etc/hw_config.sh \
    vendor/sony/sgp311/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/sony/sgp311/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/sony/sgp311/proprietary/etc/pre_hw_config.sh:system/etc/pre_hw_config.sh \
    vendor/sony/sgp311/proprietary/bin/remount:system/bin/remount \
    vendor/sony/sgp311/proprietary/bin/mac-update:system/bin/mac-update \
    vendor/sony/sgp311/proprietary/bin/illumination_service:system/bin/illumination_service \
    vendor/sony/sgp311/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/sgp311/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    vendor/sony/sgp311/proprietary/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    vendor/sony/sgp311/proprietary/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    vendor/sony/sgp311/proprietary/bin/mm-video-encdrv-test:system/bin/mm-video-encdrv-test
